services:
  - type: web
    name: login-webapp
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/dependency/webapp-runner.jar target/LoginWebApp.war --port $PORT
    envVars:
      - key: PORT
        value: 8080
      - key: MYSQLHOST
        fromSecret: MYSQLHOST
      - key: MYSQLPORT
        fromSecret: MYSQLPORT
      - key: MYSQLDATABASE
        fromSecret: MYSQLDATABASE
      - key: MYSQLUSER
        fromSecret: MYSQLUSER
      - key: MYSQLPASSWORD
        fromSecret: MYSQLPASSWORD