services:
  - type: web
    name: login-webapp
    env: java
    buildCommand: mvn clean compile
    startCommand: java -cp target/classes:target/dependency/* com.tuapp.Main
    envVars:
      - key: MYSQLHOST
        fromDatabase:
          name: railway-mysql
          property: host
      - key: MYSQLPORT
        fromDatabase:
          name: railway-mysql
          property: port
      - key: MYSQLDATABASE
        fromDatabase:
          name: railway-mysql
          property: database
      - key: MYSQLUSER
        fromDatabase:
          name: railway-mysql
          property: user
      - key: MYSQLPASSWORD
        fromDatabase:
          name: railway-mysql
          property: password