services:
  - type: web
    name: login-webapp
    env: docker
    dockerfilePath: Dockerfile  # ✅ Usa Dockerfile personalizado
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
      - key: MYSQLHOST
        fromSecret: MYSQLHOST
      - key: MYSQLPORT
        fromSecret: MYSQLPORT
      - key: MYSQLDATABASE
        fromSecret: MYSQLDATABASE
      - key: MYSQLUSER
        fromSecret: MYSQLUSER
      - key: MYSQLPASSWORD
        fromSecret: MYSQLPASSWORD